name: Deploy Static Site (ZIP) to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Zip site content
        run: zip -r site.zip .

      - name: Deploy to Azure Web App using ZIP
        uses: azure/webapps-deploy@v2
        with:
          app-name: playlistconverter
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: site.zip
